version: "3"
services:
  puppeteer-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-puppeteer-container
    volumes:
      - .:/usr/src/app
    command: ["node", "dist/index.js"]
